### ISSUE TITLE
active mqtt client

### ISSUE THREAD

**Issue by ulutomaz** [i-m-v-j/Bus#12]
Hi, 

is this project still active? I read in one of the issues that you're working on something new? I found this while reading through Hulaaki issues in regards to have that one in supervision tree. All I want is a client that could be easily be called from one Phoenix app.

Can you give any feedback on this? Thanks!

**Comment by 00imvj00** [comment]
hey, unfortunately, i stopped working on this project, but there are new really nice libraries out now for mqtt. and you can easily add them in ur phoenix app.
