### ISSUE TITLE
Connection errors with vernemq

### ISSUE THREAD

**Issue by alex88** [i-m-v-j/Bus#8]
I've tried your lib agains vernemq, this is the config:

```
config :bus,
        host: 'localhost',
        port: 1883,
        client_id: "client",
        keep_alive: 100,
        auto_reconnect: true,
        auto_connect: true,
        callback: TestProject.Callback
```

however I get tons of errors like this:

```
<0.6141.0>@vmq_ranch:teardown:115 [<0.6141.0>] session stopped abnormally due to 'cant_parse_last_will'
```

**Comment by 00imvj00** [comment]
Hello @alex88 thank you for using Bus.

i tried installing vernemq,but it seems that they don't have support for OTP 19 yet. i have come up with this article. i tested with emqttd and my other queues, it seems working fine. 

https://vernemq.com/docs/clustering/netsplits.html

i will test with vernemq and let you know.

**Comment by 00imvj00** [comment]
@alex88 hello , i think vernemq issue is resolved in latest commit. my apologies for trouble. there was small bug in bus. u can use it now.
