### ISSUE TITLE
cannot override module Bus.Callback when using exrm ....

### ISSUE THREAD

**Issue by ssachse** [i-m-v-j/Bus#9]
Hello first thanks for for your work. I was playing with your client today and it worked pretty well in iex, but as soon as I tried to deploy it to a system, I get the duplicate modules error. And sure you cannot redefine the same module .....
So I guess it would be better to do something like 

```
defmodule MyApp.Bus.Callback do
use Bus.Callback

......

```

And therefore change

```
defmodule Bus.Callback do

defmacro __using__(_) do .......

```

**Comment by 00imvj00** [comment]
Hello @ssachse thank you for trying out bus. if you want to use your own module, you can change it in config file. it is that simple. in config file you can set callback: MyApp.Bus.Callback , try this out, and let me know if still u getting issue. 

as far your suggestion, in future, i ma planning to provide multiple way of doing callbacks. and try to make as simple as possible as the same time.
